USE [master]
GO

/****** Object:  Database [Rob.EventStore]    Script Date: 08/09/2017 18:49:32 ******/
CREATE DATABASE [Rob.EventStore]

ALTER DATABASE [Rob.EventStore] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Rob.EventStore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Rob.EventStore] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Rob.EventStore] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Rob.EventStore] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Rob.EventStore] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Rob.EventStore] SET ARITHABORT OFF 
GO

ALTER DATABASE [Rob.EventStore] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Rob.EventStore] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Rob.EventStore] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Rob.EventStore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Rob.EventStore] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Rob.EventStore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Rob.EventStore] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Rob.EventStore] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Rob.EventStore] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Rob.EventStore] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Rob.EventStore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Rob.EventStore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Rob.EventStore] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Rob.EventStore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Rob.EventStore] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Rob.EventStore] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Rob.EventStore] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Rob.EventStore] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Rob.EventStore] SET  MULTI_USER 
GO

ALTER DATABASE [Rob.EventStore] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Rob.EventStore] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Rob.EventStore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Rob.EventStore] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Rob.EventStore] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Rob.EventStore] SET QUERY_STORE = OFF
GO

USE [Rob.EventStore]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Rob.EventStore] SET  READ_WRITE 
GO

USE [Rob.EventStore]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EventStore-Account](
	[AggregateId] [uniqueidentifier] NOT NULL,
	[Version] [bigint] NOT NULL,
	[EventDateTime] [datetime2](7) NOT NULL,
	[Payload] [nvarchar](max) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

